<?php 
    $database = \Drupal::database();
    function reservation_theme($existing, $type, $theme, $path) {
        return array(
        'reservation' => array(
            'variables' => array('movies' => array(), 'title' => '', 'genres' => array(), 'reservations' => array()),
        ),
        'book-showcase' => array(
            'variables' => array('books' => array(), 'title' => ''),
        ),
    );
    }

?>
